### ISSUE TITLE
[BUG] Mod config menus dont close correctly and interact weirdly

### ISSUE THREAD

**Issue by KlaasWhite** [SpaceWarpDev/SpaceWarp#103] opened 2023-03-01 20:21 UTC
###### **KSP 2 Version**
0.1.0.0.20892

###### **Space Warp Version**
0.3.0

------------------------------

###### **Describe the bug**
When using the Mod menu on the main menu, some things go wrong. 
Firstly the buttons behind the window can be interacted with, which leads to overlapping menus, I dont know if this can be easily changed but I think it would be a more logical solution

The mod menu itself has no apparent way to be closed (except for clicking the mod menu button again which seems a weird way)

(This is caused by another bug which I will file a seperate report for, but still kind of a bug)
More importantly, the Configure menu can not be closed (pressing the save and close button does nothing) and when pressing the Configure button again, another configuration menu opens, which seems counter intuitive. It seems like this is caused by a lack of config file, but i feel like it should still allow me to close the window

###### **To Reproduce**
Use the Mods menu, not much more to describe.

###### **Expected behavior**
This is a kind of both feature and bug report, I think I describe everything I would expect in the "Describe the bug" part. 

###### **Screenshots**
![image](https://user-images.githubusercontent.com/45828001/222254403-ee1b7b26-6c31-4c7f-85ed-98439c54b3c5.png)

###### **Log**
[Ksp2.log](https://github.com/SpaceWarpDev/SpaceWarp/files/10864949/Ksp2.log)

**Comment by cheese3660** [comment] 2023-03-01 20:25
For the first part, that would require a reimplementation of click through blocker which is under the LGPL license, meaning we'd likely have to port it in a separate repo under that license, compile it and have it as a dependency for space warp.
Configuration menu closing is planned, once I figure out how to put a part of the menu on the title bar, or I could just add a close button at the bottom
The inability to close is more so caused by the lack of a config folder in the mod directory

**Comment by cheese3660** [comment] 2023-03-01 21:16
It should add a config folder and config file, right now it only does the latter

**Comment by EwyBoy** [comment] 2023-03-05 13:18
Most of these issues should be fixed in the next version of SpaceWarp _(v0.4.0)_
We hope to get #49 working very soon and we have also implemented #116 and #121 and also make some improvements to the closing UI logic.

**Comment by EwyBoy** [comment] 2023-03-12 00:17
Marking this as resolved, as SpaceWarp v0.4.0 added the close button to the UI and you can also close all UI's by pressing ESC

**Closed by EwyBoy** 2023-03-12 00:17 UTC
Labels: bug
